version: '3.8'

services:
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
      - "443:443"
    volumes:
    # Montando paths em modo somente leitura
      - ./html:/usr/share/nginx/html:ro
      - ./nginx:/etc/nginx:ro
      - ./cert:/cert:ro
    restart: unless-stopped  # Reinicia o contêiner a menos que seja parado manualmente
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: overlay  # Cria uma rede overlay caso esteja utilizando docker swarm ou kubernetes para o Nginx